import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { SpeedInsights } from "@vercel/speed-insights/next";
import ConvexClerkProvider from "./ConvexClerkProvider";
import { Analytics } from "@vercel/analytics/react";
import Header from "../components/Header";
import Sidebar from "../components/Sidebar";
import MainContent from "../components/MainContent";
import Toaster from "../components/ui/toaster";
import CoreLayout from "../components/CoreLayout";

const geistSansFont = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
});
const geistMonoFont = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <ConvexClerkProvider>
      <Analytics>
        <html lang="en">
          <SpeedInsights>
            <div>
              <Toaster />
              <body className={`${geistSansFont.variable} ${geistMonoFont.variable}`}>
                <CoreLayout>
                  <Header />
                  <div className="flex flex-1 overflow-hidden">
                    <Sidebar />
                    <MainContent>{children}</MainContent>
                  </div>
                </CoreLayout>
              </body>
            </div>
          </SpeedInsights>
        </html>
      </Analytics>
    </ConvexClerkProvider>
  );
}
